=== hadron-lang/hadron/hadron.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "config": {
      "type": "object",
      "properties": {
        "implicitOverload": {
          "type": "boolean",
          "description": "Enabling allows overloading without decorators.",
          "default": false
        }
      }
    },
    "$schema": {
      "type": "string",
      "oneOf": [
        {
          "const": "https://webd3vs.xyz/hadron.schema.json"
        },
        {
          "const": "./hadron.schema.json"
        }
      ]
    },
    "name": {
      "type": "string"
    },
    "identifier": {
      "type": "string",
      "pattern": "^[a-z0-9-]+$"
    },
    "version": {
      "type": "string",
      "pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
    },
    "description": {
      "type": "string"
    },
    "author": {
      "oneOf": [
        {
          "type": "string"
        },
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "email": {
              "type": "string",
              "format": "email"
            },
            "website": {
              "type": "string",
              "format": "uri"
            }
          }
        }
      ]
    },
    "authors": {
      "type": "array",
      "items": {
        "oneOf": [
          {
            "type": "string"
          },
          {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "email": {
                "type": "string",
                "format": "email"
              },
              "website": {
                "type": "string",
                "format": "uri"
              }
            }
          }
        ]
      }
    },
    "license": {
      "type": "string"
    },
    "dependencies": {
      "type": "object",
      "additionalProperties": {
        "type": "string",
        "pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
      }
    }
  },
  "required": [
    "identifier",
    "version"
  ],
  "additionalProperties": false
}

=== hadron-lang/hadron/hadron.config.json
{
  "$schema": "./hadron.schema.json",
  "name": "My Hadron App",
  "identifier": "my-hadron-app",
  "version": "15.0.0",
  "description": "My Hadron App",
  "license": "MIT",
  "author": {
    "name": "John Doe",
    "email": "john.doe@wxample.com",
    "website": "https://example.com"
  },
  "dependencies": {
    "hadron": "15.0.0"
  },
  "config": {
    "implicitOverload": true
  }
}
